# Generated by Django 3.2.8 on 2022-01-10 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211215_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.CharField(default="prueba", max_length=400),
            preserve_default=False,
        ),
    ]
