# Generated by Django 3.2.8 on 2022-01-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.CharField(default='0000000', max_length=400),
        ),
    ]
