# Generated by Django 3.2.8 on 2022-01-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
